const CARD_FLIP = 'CARD_FLIP';
const CARD_MATCHED = 'CARD_MATCHED';
const ADD_NEW_DECK = 'ADD_NEW_DECK';
const CARD_SELECTED = 'CARD_SELECTED';
const UPDATE_SCORE = 'UPDATE_SCORE';
const UPDATE_NUMBER_OF_CARDS = 'UPDATE_NUMBER_OF_CARDS';
const CARDS_MATCHED = 'CARDS_MATCHED';

export default {
  CARD_FLIP,
  CARD_MATCHED,
  ADD_NEW_DECK,
  CARD_SELECTED,
  UPDATE_SCORE,
  UPDATE_NUMBER_OF_CARDS,
  CARDS_MATCHED,
};
